
-- create
CREATE TABLE GROUPMATES (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  age INTEGER NOT NULL,
  adress TEXT NOT NULL
);

-- insert
INSERT INTO GROUPMATES VALUES (0001, 'Evgeniy', 35, 'Nizhniy Novgorod');
INSERT INTO GROUPMATES VALUES (0002, 'Alisa', 31,'Moscow');
INSERT INTO GROUPMATES VALUES (0003, 'Alexandr', 18,'Moscow');
INSERT INTO GROUPMATES VALUES (0004, 'Valeria', 25, 'Archangelsk');
INSERT INTO GROUPMATES VALUES (0005, 'Nikita', 28, 'Moscow');
INSERT INTO GROUPMATES VALUES (0006, 'Julia', 26, 'Orel');
INSERT INTO GROUPMATES VALUES (0007, 'Kirill', 30, 'Kazan');
INSERT INTO GROUPMATES VALUES (0008, 'Maria', 41, 'Kursk');

-- fetch 
SELECT name FROM GROUPMATES WHERE age BETWEEN 18 AND 30 AND adress = 'Moscow';